server:
  port: 8014
spring:
  application:
    name: api-order-submit
  redis:
    port: 7001
    host: 8.140.225.7
    database: 0
    password: wood1234
  rabbitmq:
    host: 8.140.225.7
    port: 5672
    virtual-host: host1
    username: zhangsan
    password: admin123
  zipkin:
    enabled: true
    base-url:  http://localhost:9411
  sleuth:
    sampler:
      probability: 1
eureka:
  client:
    service-url:
      defaultZone: http://zhangsan:123456@localhost:8761/eureka

## 开启熔断器
feign:
  hystrix:
    enabled: true

