server:
  port: 8001
spring:
  application:
    name: api-user-login
  redis:
    port: 7001
    host: 8.140.225.7
    database: 0
    password: wood1234
eureka:
  client:
    service-url:
      defaultZone: http://zhangsan:123456@localhost:8761/eureka

## 开启熔断器
feign:
  hystrix:
    enabled: true

